### PR TITLE
fix(intellij): add dart sdk constraint to language server

### LINKED ISSUE #4468: fix: Unable to install Bloc Tools due to Dart version constraint
**Description**
When opening VSCode an error occurs. I couldn't find logs in any of the output channels, so no idea what's the reason.

**Steps To Reproduce**
1. Open vscode
2. getting this :(

**Screenshots**
Image

**Additional Context**
VSCode version: 1.99.3 (Universal)
Bloc extension version: 6.8.2

### PR DESCRIPTION
**Pull request by vmichalak**
## Status

**READY**

## Breaking Changes

NO

## Description

Fix #4468 for IntelliJ

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt [hunk 1]
```diff
@@ -1,27 +1,46 @@
...
 import com.redhat.devtools.lsp4ij.server.StreamConnectionProvider
 import java.util.concurrent.TimeUnit
+import java.util.concurrent.atomic.AtomicBoolean
 
-class BlocLanguageServerFactory : LanguageServerFactory {
+class BlocLanguageServerFactory : LanguageServerFactory, LanguageServerEnablementSupport {
     private val logger = Logger.getInstance(BlocLanguageServerFactory::class.java)
+    private val minVersionAlertShowed = AtomicBoolean(false)
     private val targetBlocToolsVersion = "0.1.0-dev.11"
+    private val minDartVersion = "3.7.1"
```
Comment (felangel) [inline extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt:19]:
```suggestion
    private val minDartVersion = "3.7.0"
```

Comment (vmichalak) [reply extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt]: Already fixed :D

File: extensions/intellij/intellij_generator_plugin/src/test/kotlin/com/bloc/intellij_generator_plugin/util/VersionComparatorTest.kt [hunk 2]
```diff
@@ -0,0 +1,79 @@
+package com.bloc.intellij_generator_plugin.util
+
+import kotlin.test.Test
+import kotlin.test.assertFalse
+import kotlin.test.assertTrue
+
+class VersionComparatorTest {
```
Comment (felangel) [inline extensions/intellij/intellij_generator_plugin/src/test/kotlin/com/bloc/intellij_generator_plugin/util/VersionComparatorTest.kt:7]: Thanks for adding tests! 💯

File: extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt [hunk 3]
```diff
@@ -63,4 +83,31 @@ class BlocLanguageServerFactory : LanguageServerFactory {
...
+            if (!installOrUpgradeBlocTools(project, isUpgrade)) {
+                logger.error("bloc_tools ${if (isUpgrade) "upgrade" else "installation"} failed")
+                return false
+            }
+        }
+        return true
+    }
+
+    override fun setEnabled(enabled: Boolean, project: Project) {
+        // TODO: Implement this with settings
```
[the remark this answers is not in the document]
Comment (vmichalak) [reply extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt:111]: As you can see on the [documentation](https://github.com/redhat-developer/lsp4ij/blob/main/docs/DeveloperGuide.md#enable--disable) of LSP4IJ, this setter is for permitting to add an option to programmatically set on and off the LSP. We gonna use it to add an option to disable the LSP in near future but it's outside of this PR scope i think.

**Comment by vmichalak** [comment]
Little refactor added

File: extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt [hunk 4]
```diff
@@ -63,4 +71,31 @@ class BlocLanguageServerFactory : LanguageServerFactory {
             .createNotification(content, type)
             .notify(project)
     }
+
+    override fun isEnabled(project: Project): Boolean {
+        val blocToolsVersion = getBlocToolsVersion()
```
Comment (felangel) [inline extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServerFactory.kt:76]: Looks like this method is being called many times and results in a really laggy user experience so we should probably rework this.

File: extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt [hunk 5]
```diff
@@ -1,6 +1,97 @@
...
+        private const val TARGET_BLOC_TOOLS_VERSION = "0.1.0-dev.11"
+        private const val MIN_DART_VERSION = "3.7.0"
+    }
+
+    private val logger = Logger.getInstance(BlocLanguageServer::class.java)
+    private val minVersionAlertShowed = AtomicBoolean(false)
+    private val dartVersionRegex = Regex("Dart SDK version: ((?:[0-9]*\\.?)*)")
+
+    override fun start() {
+        if (project != null && checkRequirements(project)) {
```
Comment (felangel) [inline extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt:27]:
```suggestion
        if (project == null || !checkRequirements(project)) {
```

Isn't this logic slightly incorrect? I thought `checkRequirements` returns `true` if the requirements are met.

**Review by felangel — APPROVED** [review]
LGTM ✅ 
Thanks as always for the contributions! 🙏

File: extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt (hunk 5 above)
Comment (vmichalak) [reply extensions/intellij/intellij_generator_plugin/src/main/java/com/bloc/intellij_generator_plugin/language_server/BlocLanguageServer.kt]: Yeah it's an issue on my side
