### PR TITLE
fix(vscode): show context menu conditionally

### LINKED ISSUE #3948: fix(vscode): do not show context menu contributions when not in a Bloc project
**Description**

Currently, the Bloc visual studio code extension always shows the options "Bloc: New Bloc" and "Bloc: New Cubit". This violates the [VS Code's UX recommendation](https://code.visualstudio.com/api/ux-guidelines/context-menus).

I would like these options to only show when the project (workspace) currently being worked on is a Dart project and it has a bloc dependency on the _pubspec.yaml_.

**Steps To Reproduce**

1. [Install the Bloc VS Code extension](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc).
2. Right click on a directory within the VS Code file explorer.
3. The options "Bloc: New Bloc" and "Bloc: New Cubit" are shown.

**Expected Behavior**
The options "Bloc: New Bloc" and "Bloc: New Cubit" should only be shown when project is a Dart project and has a bloc dependency on the _pubspec.yaml_.

**Video**

<details> 

<summary> Showing in a Dart project without a `bloc` dependency </summary>

https://github.com/felangel/bloc/assets/44524995/2aa2012c-c076-419e-8739-26248521d419

</details>

<details> 

<summary> Showing in a Node project </summary>

https://github.com/felangel/bloc/assets/44524995/8cd1bb66-0bae-4d71-bf84-dd91effdab25

</details>

**Additional Context**

- [VS Code's UX Context Menu recommendation](https://code.visualstudio.com/api/ux-guidelines/context-menus)

### PR DESCRIPTION
**Pull request by alestiago**
## Status

**READY**

> **Note**: Since the extension has no tests, I recommend verifying the behaviour manually locally.

## Breaking Changes

NO

## Description

Resolves #3948

## Demonstration

https://github.com/felangel/bloc/assets/44524995/00adc0fb-e09b-4515-9bd8-65e26fa4cc39

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by tenhobi** [comment]
The code looks good! It's simpler than I expected haha.

Any tips on how I can test that locally?

**Comment by alestiago** [comment]
@tenhobi thanks for the comment. I'm glad it looks simple that's part of the aim!

---

The steps for testing it locally are the following:

1. Clone the repository and open `extensions/vscode` directory.

2. Install all dependencies.
```sh
npm i
```

3. Compile the project:
```sh
npm run compile
```

Compilation should succeed, if it does't let me know.

4. Run the project on a Development Host Window by pressing F5 and selecting it as a target.

5. From the Development Host Window open a sample project in your directory to play around with.

> **Note**: I think it will be good idea to include CONTRIBUTING information with all these steps, you may want to take inspiration from [Dart Frog's VS Code CONTRIBUTING](https://github.com/VeryGoodOpenSource/dart_frog/blob/main/extensions/vscode/CONTRIBUTING.md).

File: extensions/vscode/src/extension.ts [hunk 1]
```diff
@@ -66,3 +92,64 @@ export function activate(_context: ExtensionContext) {
...
+ *
+ * @param pubspec The pubspec to check.
+ * @returns {Promise<boolean>} true if the pubspec has a Bloc dependency, or false otherwise.
+ */
+async function hasBlocDependency(pubspec: Uri): Promise<boolean> {
+  try {
+    const content = await workspace.fs.readFile(pubspec);
+    const yamlContent = yaml.load(content.toString());
+    const dependencies = _.get(yamlContent, "dependencies", {});
+    return _.has(dependencies, "bloc") || _.has(dependencies, "flutter_bloc");
```
Comment (felangel) [inline extensions/vscode/src/extension.ts:152]: technically it can also depend on `hydrated_bloc` or `replay_bloc`.

File: extensions/vscode/src/extension.ts [hunk 2]
```diff
@@ -19,12 +27,30 @@ import { BlocCodeActionProvider } from "./code-actions";
...
   if (workspace.getConfiguration("bloc").get<boolean>("checkForUpdates")) {
     analyzeDependencies();
   }
 
+  updateAnyBlocProjectLoaded();
+
   _context.subscriptions.push(
+    window.onDidChangeActiveTextEditor(updateAnyBlocProjectLoaded),
+    workspace.onDidChangeWorkspaceFolders(updateAnyBlocProjectLoaded),
+    workspace.onDidChangeTextDocument(async (event) => {
```
Comment (felangel) [inline extensions/vscode/src/extension.ts:44]: why is `onDidChangeTextDocument` needed? That seems like it would be quite heavy if we're recursively analyzing `pubspec.yaml` files every time a text document changes.

**Review by felangel — APPROVED** [review]
LGTM thanks so much for taking the time to do this! 💙
