### PR TITLE
fix: sign up cubit password confirmation order

### LINKED ISSUE #2179: Signup Cubit issue with password confirmation order
**Describe the bug**
There is a bug on the signup screen (SignUp Cubit) if the user enters the password confirmation first and after that the password.
Even if both passwords match exactly, the SignUp Button will stay disabled. You then have to erase a character from the password field and re-type.

**To Reproduce**
Go to the sign up screen, and type a 6 character (or more) password in the ConfirmPasswordInput field, then repeat the same password in the PasswordInput field => The SignUp Button will still be disabled

**Expected behavior**
The order in which the password and confirmed password are typed should not matter. 

**Solution**
In the SignUp Cubit, change the passwordChanged function. The "status" parameter should take the variable confirmedPassword (instead of currently state.confirmedPassword)

### PR DESCRIPTION
**Pull request by duan-daniel**
## Status

**READY**

## Breaking Changes

NO

## Description

* Updates `SignUp Cubit` so that the `SignUp Button` will be enabled if both passwords match, regardless of the order in which the passwords were inputted. 
* closes #2179 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart [hunk 1]
```diff
@@ -35,7 +35,7 @@ class SignUpCubit extends Cubit<SignUpState> {
       status: Formz.validate([
         state.email,
         password,
-        state.confirmedPassword,
+        confirmedPassword,
```
Comment (felangel) [inline examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart:38]: Nice find! Can we add a unit test to ensure this bug I’d never reintroduced?

**Review by felangel — CHANGES_REQUESTED** [review]
Great job! Can we just add a unit test to prevent a regression?

**Review by felangel — APPROVED** [review]
LGTM thanks so much for the contribution! 🚀
